# Request
string object_name  # Name of the object to search for
bool use_sim        # True if using Isaac Sim 
project_interfaces/TransformMatrix transform #trasformation matrix for non-stationary camera 

---
# Response
int32 object_count                  # The number of objects found
DetectedObject[] detected_objects   # nested msg´es as ROS cant take nested arrays. |-;
