// generated from rosidl_generator_cpp/resource/idl.hpp.em
// generated code does not contain a copyright notice

#ifndef ROBOTIQ_3F_GRIPPER_ROS2_INTERFACES__MSG__ROBOTIQ3_F_GRIPPER_OUTPUT_REGISTERS_HPP_
#define ROBOTIQ_3F_GRIPPER_ROS2_INTERFACES__MSG__ROBOTIQ3_F_GRIPPER_OUTPUT_REGISTERS_HPP_

#include "robotiq_3f_gripper_ros2_interfaces/msg/detail/robotiq3_f_gripper_output_registers__struct.hpp"
#include "robotiq_3f_gripper_ros2_interfaces/msg/detail/robotiq3_f_gripper_output_registers__builder.hpp"
#include "robotiq_3f_gripper_ros2_interfaces/msg/detail/robotiq3_f_gripper_output_registers__traits.hpp"

#endif  // ROBOTIQ_3F_GRIPPER_ROS2_INTERFACES__MSG__ROBOTIQ3_F_GRIPPER_OUTPUT_REGISTERS_HPP_
